spring:
  datasource:
    url: jdbc:mysql://101.37.159.5:3306/election?setUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2b8
    username: root
    password: D32ed5c966c7
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 60000
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
