package com.mou.election.dal.mapper;

import com.mou.election.dal.domian.EAnswerDO;
import com.mou.election.dal.domian.EAnswerDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EAnswerDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_answer
     *
     * @mbggenerated Sat Jul 17 01:48:51 CST 2021
     */
    int countByExample(EAnswerDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_answer
     *
     * @mbggenerated Sat Jul 17 01:48:51 CST 2021
     */
    int deleteByExample(EAnswerDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_answer
     *
     * @mbggenerated Sat Jul 17 01:48:51 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_answer
     *
     * @mbggenerated Sat Jul 17 01:48:51 CST 2021
     */
    int insert(EAnswerDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_answer
     *
     * @mbggenerated Sat Jul 17 01:48:51 CST 2021
     */
    int insertSelective(EAnswerDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_answer
     *
     * @mbggenerated Sat Jul 17 01:48:51 CST 2021
     */
    List<EAnswerDO> selectByExample(EAnswerDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_answer
     *
     * @mbggenerated Sat Jul 17 01:48:51 CST 2021
     */
    EAnswerDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_answer
     *
     * @mbggenerated Sat Jul 17 01:48:51 CST 2021
     */
    int updateByExampleSelective(@Param("record") EAnswerDO record, @Param("example") EAnswerDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_answer
     *
     * @mbggenerated Sat Jul 17 01:48:51 CST 2021
     */
    int updateByExample(@Param("record") EAnswerDO record, @Param("example") EAnswerDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_answer
     *
     * @mbggenerated Sat Jul 17 01:48:51 CST 2021
     */
    int updateByPrimaryKeySelective(EAnswerDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_answer
     *
     * @mbggenerated Sat Jul 17 01:48:51 CST 2021
     */
    int updateByPrimaryKey(EAnswerDO record);
}