package com.mou.election.dal.mapper;

import com.mou.election.dal.domian.EApplyDO;
import com.mou.election.dal.domian.EApplyDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EApplyDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_apply
     *
     * @mbggenerated Thu Jul 08 00:10:05 CST 2021
     */
    int countByExample(EApplyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_apply
     *
     * @mbggenerated Thu Jul 08 00:10:05 CST 2021
     */
    int deleteByExample(EApplyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_apply
     *
     * @mbggenerated Thu Jul 08 00:10:05 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_apply
     *
     * @mbggenerated Thu Jul 08 00:10:05 CST 2021
     */
    int insert(EApplyDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_apply
     *
     * @mbggenerated Thu Jul 08 00:10:05 CST 2021
     */
    int insertSelective(EApplyDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_apply
     *
     * @mbggenerated Thu Jul 08 00:10:05 CST 2021
     */
    List<EApplyDO> selectByExample(EApplyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_apply
     *
     * @mbggenerated Thu Jul 08 00:10:05 CST 2021
     */
    EApplyDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_apply
     *
     * @mbggenerated Thu Jul 08 00:10:05 CST 2021
     */
    int updateByExampleSelective(@Param("record") EApplyDO record, @Param("example") EApplyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_apply
     *
     * @mbggenerated Thu Jul 08 00:10:05 CST 2021
     */
    int updateByExample(@Param("record") EApplyDO record, @Param("example") EApplyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_apply
     *
     * @mbggenerated Thu Jul 08 00:10:05 CST 2021
     */
    int updateByPrimaryKeySelective(EApplyDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_apply
     *
     * @mbggenerated Thu Jul 08 00:10:05 CST 2021
     */
    int updateByPrimaryKey(EApplyDO record);
}