package com.mou.election.dal.mapper;

import com.mou.election.dal.domian.EdataDictionaryDO;
import com.mou.election.dal.domian.EdataDictionaryDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EdataDictionaryDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_data_dictionary
     *
     * @mbggenerated Sat Jul 03 07:13:55 CST 2021
     */
    int countByExample(EdataDictionaryDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_data_dictionary
     *
     * @mbggenerated Sat Jul 03 07:13:55 CST 2021
     */
    int deleteByExample(EdataDictionaryDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_data_dictionary
     *
     * @mbggenerated Sat Jul 03 07:13:55 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_data_dictionary
     *
     * @mbggenerated Sat Jul 03 07:13:55 CST 2021
     */
    int insert(EdataDictionaryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_data_dictionary
     *
     * @mbggenerated Sat Jul 03 07:13:55 CST 2021
     */
    int insertSelective(EdataDictionaryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_data_dictionary
     *
     * @mbggenerated Sat Jul 03 07:13:55 CST 2021
     */
    List<EdataDictionaryDO> selectByExample(EdataDictionaryDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_data_dictionary
     *
     * @mbggenerated Sat Jul 03 07:13:55 CST 2021
     */
    EdataDictionaryDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_data_dictionary
     *
     * @mbggenerated Sat Jul 03 07:13:55 CST 2021
     */
    int updateByExampleSelective(@Param("record") EdataDictionaryDO record, @Param("example") EdataDictionaryDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_data_dictionary
     *
     * @mbggenerated Sat Jul 03 07:13:55 CST 2021
     */
    int updateByExample(@Param("record") EdataDictionaryDO record, @Param("example") EdataDictionaryDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_data_dictionary
     *
     * @mbggenerated Sat Jul 03 07:13:55 CST 2021
     */
    int updateByPrimaryKeySelective(EdataDictionaryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_data_dictionary
     *
     * @mbggenerated Sat Jul 03 07:13:55 CST 2021
     */
    int updateByPrimaryKey(EdataDictionaryDO record);
}