package com.mou.election.dal.mapper;

import com.mou.election.dal.domian.EExamDO;
import com.mou.election.dal.domian.EExamDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EExamDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_exam
     *
     * @mbggenerated Sat Jul 17 22:44:00 CST 2021
     */
    int countByExample(EExamDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_exam
     *
     * @mbggenerated Sat Jul 17 22:44:00 CST 2021
     */
    int deleteByExample(EExamDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_exam
     *
     * @mbggenerated Sat Jul 17 22:44:00 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_exam
     *
     * @mbggenerated Sat Jul 17 22:44:00 CST 2021
     */
    int insert(EExamDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_exam
     *
     * @mbggenerated Sat Jul 17 22:44:00 CST 2021
     */
    int insertSelective(EExamDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_exam
     *
     * @mbggenerated Sat Jul 17 22:44:00 CST 2021
     */
    List<EExamDO> selectByExample(EExamDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_exam
     *
     * @mbggenerated Sat Jul 17 22:44:00 CST 2021
     */
    EExamDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_exam
     *
     * @mbggenerated Sat Jul 17 22:44:00 CST 2021
     */
    int updateByExampleSelective(@Param("record") EExamDO record, @Param("example") EExamDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_exam
     *
     * @mbggenerated Sat Jul 17 22:44:00 CST 2021
     */
    int updateByExample(@Param("record") EExamDO record, @Param("example") EExamDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_exam
     *
     * @mbggenerated Sat Jul 17 22:44:00 CST 2021
     */
    int updateByPrimaryKeySelective(EExamDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_exam
     *
     * @mbggenerated Sat Jul 17 22:44:00 CST 2021
     */
    int updateByPrimaryKey(EExamDO record);
}