package com.mou.election.dal.mapper;

import com.mou.election.dal.domian.EmessageDO;
import com.mou.election.dal.domian.EmessageDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmessageDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    int countByExample(EmessageDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    int deleteByExample(EmessageDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    int insert(EmessageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    int insertSelective(EmessageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    List<EmessageDO> selectByExample(EmessageDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    EmessageDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    int updateByExampleSelective(@Param("record") EmessageDO record, @Param("example") EmessageDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    int updateByExample(@Param("record") EmessageDO record, @Param("example") EmessageDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    int updateByPrimaryKeySelective(EmessageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    int updateByPrimaryKey(EmessageDO record);
}