package com.mou.election.dal.mapper;

import com.mou.election.dal.domian.EmessageTypeDO;
import com.mou.election.dal.domian.EmessageTypeDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmessageTypeDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_message_type
     *
     * @mbggenerated Sat Jul 03 20:36:15 CST 2021
     */
    int countByExample(EmessageTypeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_message_type
     *
     * @mbggenerated Sat Jul 03 20:36:15 CST 2021
     */
    int deleteByExample(EmessageTypeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_message_type
     *
     * @mbggenerated Sat Jul 03 20:36:15 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_message_type
     *
     * @mbggenerated Sat Jul 03 20:36:15 CST 2021
     */
    int insert(EmessageTypeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_message_type
     *
     * @mbggenerated Sat Jul 03 20:36:15 CST 2021
     */
    int insertSelective(EmessageTypeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_message_type
     *
     * @mbggenerated Sat Jul 03 20:36:15 CST 2021
     */
    List<EmessageTypeDO> selectByExample(EmessageTypeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_message_type
     *
     * @mbggenerated Sat Jul 03 20:36:15 CST 2021
     */
    EmessageTypeDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_message_type
     *
     * @mbggenerated Sat Jul 03 20:36:15 CST 2021
     */
    int updateByExampleSelective(@Param("record") EmessageTypeDO record, @Param("example") EmessageTypeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_message_type
     *
     * @mbggenerated Sat Jul 03 20:36:15 CST 2021
     */
    int updateByExample(@Param("record") EmessageTypeDO record, @Param("example") EmessageTypeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_message_type
     *
     * @mbggenerated Sat Jul 03 20:36:15 CST 2021
     */
    int updateByPrimaryKeySelective(EmessageTypeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_message_type
     *
     * @mbggenerated Sat Jul 03 20:36:15 CST 2021
     */
    int updateByPrimaryKey(EmessageTypeDO record);
}