package com.mou.election.dal.mapper;

import com.mou.election.dal.domian.EorganizationDO;
import com.mou.election.dal.domian.EorganizationDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EorganizationDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_organization
     *
     * @mbggenerated Sun Jul 04 10:34:34 CST 2021
     */
    int countByExample(EorganizationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_organization
     *
     * @mbggenerated Sun Jul 04 10:34:34 CST 2021
     */
    int deleteByExample(EorganizationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_organization
     *
     * @mbggenerated Sun Jul 04 10:34:34 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_organization
     *
     * @mbggenerated Sun Jul 04 10:34:34 CST 2021
     */
    int insert(EorganizationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_organization
     *
     * @mbggenerated Sun Jul 04 10:34:34 CST 2021
     */
    int insertSelective(EorganizationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_organization
     *
     * @mbggenerated Sun Jul 04 10:34:34 CST 2021
     */
    List<EorganizationDO> selectByExample(EorganizationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_organization
     *
     * @mbggenerated Sun Jul 04 10:34:34 CST 2021
     */
    EorganizationDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_organization
     *
     * @mbggenerated Sun Jul 04 10:34:34 CST 2021
     */
    int updateByExampleSelective(@Param("record") EorganizationDO record, @Param("example") EorganizationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_organization
     *
     * @mbggenerated Sun Jul 04 10:34:34 CST 2021
     */
    int updateByExample(@Param("record") EorganizationDO record, @Param("example") EorganizationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_organization
     *
     * @mbggenerated Sun Jul 04 10:34:34 CST 2021
     */
    int updateByPrimaryKeySelective(EorganizationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_organization
     *
     * @mbggenerated Sun Jul 04 10:34:34 CST 2021
     */
    int updateByPrimaryKey(EorganizationDO record);
}