package com.mou.election.dal.mapper;

import com.mou.election.dal.domian.EpermissionDO;
import com.mou.election.dal.domian.EpermissionDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EpermissionDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_permission
     *
     * @mbggenerated Wed Jul 07 01:00:38 CST 2021
     */
    int countByExample(EpermissionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_permission
     *
     * @mbggenerated Wed Jul 07 01:00:38 CST 2021
     */
    int deleteByExample(EpermissionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_permission
     *
     * @mbggenerated Wed Jul 07 01:00:38 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_permission
     *
     * @mbggenerated Wed Jul 07 01:00:38 CST 2021
     */
    int insert(EpermissionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_permission
     *
     * @mbggenerated Wed Jul 07 01:00:38 CST 2021
     */
    int insertSelective(EpermissionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_permission
     *
     * @mbggenerated Wed Jul 07 01:00:38 CST 2021
     */
    List<EpermissionDO> selectByExample(EpermissionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_permission
     *
     * @mbggenerated Wed Jul 07 01:00:38 CST 2021
     */
    EpermissionDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_permission
     *
     * @mbggenerated Wed Jul 07 01:00:38 CST 2021
     */
    int updateByExampleSelective(@Param("record") EpermissionDO record, @Param("example") EpermissionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_permission
     *
     * @mbggenerated Wed Jul 07 01:00:38 CST 2021
     */
    int updateByExample(@Param("record") EpermissionDO record, @Param("example") EpermissionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_permission
     *
     * @mbggenerated Wed Jul 07 01:00:38 CST 2021
     */
    int updateByPrimaryKeySelective(EpermissionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_permission
     *
     * @mbggenerated Wed Jul 07 01:00:38 CST 2021
     */
    int updateByPrimaryKey(EpermissionDO record);
}