package com.mou.election.dal.mapper;

import com.mou.election.dal.domian.EQuestionDO;
import com.mou.election.dal.domian.EQuestionDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EQuestionDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_question
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    int countByExample(EQuestionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_question
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    int deleteByExample(EQuestionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_question
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_question
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    int insert(EQuestionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_question
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    int insertSelective(EQuestionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_question
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    List<EQuestionDO> selectByExample(EQuestionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_question
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    EQuestionDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_question
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    int updateByExampleSelective(@Param("record") EQuestionDO record, @Param("example") EQuestionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_question
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    int updateByExample(@Param("record") EQuestionDO record, @Param("example") EQuestionDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_question
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    int updateByPrimaryKeySelective(EQuestionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_question
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    int updateByPrimaryKey(EQuestionDO record);
}