package com.mou.election.dal.mapper;

import com.mou.election.dal.domian.EResultDO;
import com.mou.election.dal.domian.EResultDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EResultDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_result
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    int countByExample(EResultDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_result
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    int deleteByExample(EResultDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_result
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_result
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    int insert(EResultDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_result
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    int insertSelective(EResultDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_result
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    List<EResultDO> selectByExample(EResultDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_result
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    EResultDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_result
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    int updateByExampleSelective(@Param("record") EResultDO record, @Param("example") EResultDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_result
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    int updateByExample(@Param("record") EResultDO record, @Param("example") EResultDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_result
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    int updateByPrimaryKeySelective(EResultDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_result
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    int updateByPrimaryKey(EResultDO record);
}