package com.mou.election.dal.mapper;

import com.mou.election.dal.domian.EuserMessageDO;
import com.mou.election.dal.domian.EuserMessageDOExample;
import java.util.List;

import com.mou.election.dal.domian.EuserMessageJoinDO;
import com.mou.election.dal.domian.EuserMessageJoinUserDO;
import org.apache.ibatis.annotations.Param;

public interface EuserMessageDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_user_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    int countByExample(EuserMessageDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_user_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    int deleteByExample(EuserMessageDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_user_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_user_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    int insert(EuserMessageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_user_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    int insertSelective(EuserMessageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_user_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    List<EuserMessageDO> selectByExample(EuserMessageDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_user_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    EuserMessageDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_user_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    int updateByExampleSelective(@Param("record") EuserMessageDO record, @Param("example") EuserMessageDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_user_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    int updateByExample(@Param("record") EuserMessageDO record, @Param("example") EuserMessageDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_user_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    int updateByPrimaryKeySelective(EuserMessageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_user_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    int updateByPrimaryKey(EuserMessageDO record);

    List<EuserMessageJoinDO> findUserMessageJoin(String userAttr);

    List<EuserMessageJoinUserDO> findUserMessageJoinByIsReceipt(String messageId);

    List<EuserMessageJoinDO> findUserMessageJoinByIsCT(String userAttr);

    List<EuserMessageJoinDO> findUserMessageJoinByNotice(String userAttr);

    List<EuserMessageJoinDO> findUserMessageJoinByMessageId(@Param("phone")String phone,@Param("id") String id);
}