package com.mou.election.dal.mapper;

import com.mou.election.dal.domian.EuserDO;
import com.mou.election.dal.domian.EuserDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EuserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_user
     *
     * @mbggenerated Wed Jul 07 01:42:13 CST 2021
     */
    int countByExample(EuserDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_user
     *
     * @mbggenerated Wed Jul 07 01:42:13 CST 2021
     */
    int deleteByExample(EuserDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_user
     *
     * @mbggenerated Wed Jul 07 01:42:13 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_user
     *
     * @mbggenerated Wed Jul 07 01:42:13 CST 2021
     */
    int insert(EuserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_user
     *
     * @mbggenerated Wed Jul 07 01:42:13 CST 2021
     */
    int insertSelective(EuserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_user
     *
     * @mbggenerated Wed Jul 07 01:42:13 CST 2021
     */
    List<EuserDO> selectByExample(EuserDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_user
     *
     * @mbggenerated Wed Jul 07 01:42:13 CST 2021
     */
    EuserDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_user
     *
     * @mbggenerated Wed Jul 07 01:42:13 CST 2021
     */
    int updateByExampleSelective(@Param("record") EuserDO record, @Param("example") EuserDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_user
     *
     * @mbggenerated Wed Jul 07 01:42:13 CST 2021
     */
    int updateByExample(@Param("record") EuserDO record, @Param("example") EuserDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_user
     *
     * @mbggenerated Wed Jul 07 01:42:13 CST 2021
     */
    int updateByPrimaryKeySelective(EuserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_user
     *
     * @mbggenerated Wed Jul 07 01:42:13 CST 2021
     */
    int updateByPrimaryKey(EuserDO record);
}