package com.mou.election.dal.domian;

import java.util.Date;

public class EAnswerDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_answer.id
     *
     * @mbggenerated Sat Jul 17 01:48:51 CST 2021
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_answer.gmt_create
     *
     * @mbggenerated Sat Jul 17 01:48:51 CST 2021
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_answer.gmt_modified
     *
     * @mbggenerated Sat Jul 17 01:48:51 CST 2021
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_answer.choice
     *
     * @mbggenerated Sat Jul 17 01:48:51 CST 2021
     */
    private String choice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_answer.arrange
     *
     * @mbggenerated Sat Jul 17 01:48:51 CST 2021
     */
    private String arrange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_answer.question_id
     *
     * @mbggenerated Sat Jul 17 01:48:51 CST 2021
     */
    private Long questionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_answer.right_answer
     *
     * @mbggenerated Sat Jul 17 01:48:51 CST 2021
     */
    private Integer rightAnswer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_answer.id
     *
     * @return the value of e_answer.id
     *
     * @mbggenerated Sat Jul 17 01:48:51 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_answer.id
     *
     * @param id the value for e_answer.id
     *
     * @mbggenerated Sat Jul 17 01:48:51 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_answer.gmt_create
     *
     * @return the value of e_answer.gmt_create
     *
     * @mbggenerated Sat Jul 17 01:48:51 CST 2021
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_answer.gmt_create
     *
     * @param gmtCreate the value for e_answer.gmt_create
     *
     * @mbggenerated Sat Jul 17 01:48:51 CST 2021
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_answer.gmt_modified
     *
     * @return the value of e_answer.gmt_modified
     *
     * @mbggenerated Sat Jul 17 01:48:51 CST 2021
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_answer.gmt_modified
     *
     * @param gmtModified the value for e_answer.gmt_modified
     *
     * @mbggenerated Sat Jul 17 01:48:51 CST 2021
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_answer.choice
     *
     * @return the value of e_answer.choice
     *
     * @mbggenerated Sat Jul 17 01:48:51 CST 2021
     */
    public String getChoice() {
        return choice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_answer.choice
     *
     * @param choice the value for e_answer.choice
     *
     * @mbggenerated Sat Jul 17 01:48:51 CST 2021
     */
    public void setChoice(String choice) {
        this.choice = choice == null ? null : choice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_answer.arrange
     *
     * @return the value of e_answer.arrange
     *
     * @mbggenerated Sat Jul 17 01:48:51 CST 2021
     */
    public String getArrange() {
        return arrange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_answer.arrange
     *
     * @param arrange the value for e_answer.arrange
     *
     * @mbggenerated Sat Jul 17 01:48:51 CST 2021
     */
    public void setArrange(String arrange) {
        this.arrange = arrange == null ? null : arrange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_answer.question_id
     *
     * @return the value of e_answer.question_id
     *
     * @mbggenerated Sat Jul 17 01:48:51 CST 2021
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_answer.question_id
     *
     * @param questionId the value for e_answer.question_id
     *
     * @mbggenerated Sat Jul 17 01:48:51 CST 2021
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_answer.right_answer
     *
     * @return the value of e_answer.right_answer
     *
     * @mbggenerated Sat Jul 17 01:48:51 CST 2021
     */
    public Integer getRightAnswer() {
        return rightAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_answer.right_answer
     *
     * @param rightAnswer the value for e_answer.right_answer
     *
     * @mbggenerated Sat Jul 17 01:48:51 CST 2021
     */
    public void setRightAnswer(Integer rightAnswer) {
        this.rightAnswer = rightAnswer;
    }
}