package com.mou.election.dal.domian;

import java.util.Date;

public class EExamAnswerDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_exam_answer.id
     *
     * @mbggenerated Sun Jul 18 11:57:23 CST 2021
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_exam_answer.gmt_create
     *
     * @mbggenerated Sun Jul 18 11:57:23 CST 2021
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_exam_answer.gmt_modified
     *
     * @mbggenerated Sun Jul 18 11:57:23 CST 2021
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_exam_answer.exam_id
     *
     * @mbggenerated Sun Jul 18 11:57:23 CST 2021
     */
    private Long examId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_exam_answer.question_id
     *
     * @mbggenerated Sun Jul 18 11:57:23 CST 2021
     */
    private Long questionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_exam_answer.result
     *
     * @mbggenerated Sun Jul 18 11:57:23 CST 2021
     */
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_exam_answer.is_right
     *
     * @mbggenerated Sun Jul 18 11:57:23 CST 2021
     */
    private Integer isRight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_exam_answer.user_id
     *
     * @mbggenerated Sun Jul 18 11:57:23 CST 2021
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_exam_answer.result_id
     *
     * @mbggenerated Sun Jul 18 11:57:23 CST 2021
     */
    private Long resultId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_exam_answer.id
     *
     * @return the value of e_exam_answer.id
     *
     * @mbggenerated Sun Jul 18 11:57:23 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_exam_answer.id
     *
     * @param id the value for e_exam_answer.id
     *
     * @mbggenerated Sun Jul 18 11:57:23 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_exam_answer.gmt_create
     *
     * @return the value of e_exam_answer.gmt_create
     *
     * @mbggenerated Sun Jul 18 11:57:23 CST 2021
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_exam_answer.gmt_create
     *
     * @param gmtCreate the value for e_exam_answer.gmt_create
     *
     * @mbggenerated Sun Jul 18 11:57:23 CST 2021
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_exam_answer.gmt_modified
     *
     * @return the value of e_exam_answer.gmt_modified
     *
     * @mbggenerated Sun Jul 18 11:57:23 CST 2021
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_exam_answer.gmt_modified
     *
     * @param gmtModified the value for e_exam_answer.gmt_modified
     *
     * @mbggenerated Sun Jul 18 11:57:23 CST 2021
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_exam_answer.exam_id
     *
     * @return the value of e_exam_answer.exam_id
     *
     * @mbggenerated Sun Jul 18 11:57:23 CST 2021
     */
    public Long getExamId() {
        return examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_exam_answer.exam_id
     *
     * @param examId the value for e_exam_answer.exam_id
     *
     * @mbggenerated Sun Jul 18 11:57:23 CST 2021
     */
    public void setExamId(Long examId) {
        this.examId = examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_exam_answer.question_id
     *
     * @return the value of e_exam_answer.question_id
     *
     * @mbggenerated Sun Jul 18 11:57:23 CST 2021
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_exam_answer.question_id
     *
     * @param questionId the value for e_exam_answer.question_id
     *
     * @mbggenerated Sun Jul 18 11:57:23 CST 2021
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_exam_answer.result
     *
     * @return the value of e_exam_answer.result
     *
     * @mbggenerated Sun Jul 18 11:57:23 CST 2021
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_exam_answer.result
     *
     * @param result the value for e_exam_answer.result
     *
     * @mbggenerated Sun Jul 18 11:57:23 CST 2021
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_exam_answer.is_right
     *
     * @return the value of e_exam_answer.is_right
     *
     * @mbggenerated Sun Jul 18 11:57:23 CST 2021
     */
    public Integer getIsRight() {
        return isRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_exam_answer.is_right
     *
     * @param isRight the value for e_exam_answer.is_right
     *
     * @mbggenerated Sun Jul 18 11:57:23 CST 2021
     */
    public void setIsRight(Integer isRight) {
        this.isRight = isRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_exam_answer.user_id
     *
     * @return the value of e_exam_answer.user_id
     *
     * @mbggenerated Sun Jul 18 11:57:23 CST 2021
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_exam_answer.user_id
     *
     * @param userId the value for e_exam_answer.user_id
     *
     * @mbggenerated Sun Jul 18 11:57:23 CST 2021
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_exam_answer.result_id
     *
     * @return the value of e_exam_answer.result_id
     *
     * @mbggenerated Sun Jul 18 11:57:23 CST 2021
     */
    public Long getResultId() {
        return resultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_exam_answer.result_id
     *
     * @param resultId the value for e_exam_answer.result_id
     *
     * @mbggenerated Sun Jul 18 11:57:23 CST 2021
     */
    public void setResultId(Long resultId) {
        this.resultId = resultId;
    }
}