package com.mou.election.dal.domian;

import java.util.Date;

public class EExamDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_exam.id
     *
     * @mbggenerated Sat Jul 17 22:44:00 CST 2021
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_exam.gmt_create
     *
     * @mbggenerated Sat Jul 17 22:44:00 CST 2021
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_exam.gmt_modified
     *
     * @mbggenerated Sat Jul 17 22:44:00 CST 2021
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_exam.title
     *
     * @mbggenerated Sat Jul 17 22:44:00 CST 2021
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_exam.pass_score
     *
     * @mbggenerated Sat Jul 17 22:44:00 CST 2021
     */
    private String passScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_exam.remark
     *
     * @mbggenerated Sat Jul 17 22:44:00 CST 2021
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_exam.feature
     *
     * @mbggenerated Sat Jul 17 22:44:00 CST 2021
     */
    private String feature;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_exam.id
     *
     * @return the value of e_exam.id
     *
     * @mbggenerated Sat Jul 17 22:44:00 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_exam.id
     *
     * @param id the value for e_exam.id
     *
     * @mbggenerated Sat Jul 17 22:44:00 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_exam.gmt_create
     *
     * @return the value of e_exam.gmt_create
     *
     * @mbggenerated Sat Jul 17 22:44:00 CST 2021
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_exam.gmt_create
     *
     * @param gmtCreate the value for e_exam.gmt_create
     *
     * @mbggenerated Sat Jul 17 22:44:00 CST 2021
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_exam.gmt_modified
     *
     * @return the value of e_exam.gmt_modified
     *
     * @mbggenerated Sat Jul 17 22:44:00 CST 2021
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_exam.gmt_modified
     *
     * @param gmtModified the value for e_exam.gmt_modified
     *
     * @mbggenerated Sat Jul 17 22:44:00 CST 2021
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_exam.title
     *
     * @return the value of e_exam.title
     *
     * @mbggenerated Sat Jul 17 22:44:00 CST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_exam.title
     *
     * @param title the value for e_exam.title
     *
     * @mbggenerated Sat Jul 17 22:44:00 CST 2021
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_exam.pass_score
     *
     * @return the value of e_exam.pass_score
     *
     * @mbggenerated Sat Jul 17 22:44:00 CST 2021
     */
    public String getPassScore() {
        return passScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_exam.pass_score
     *
     * @param passScore the value for e_exam.pass_score
     *
     * @mbggenerated Sat Jul 17 22:44:00 CST 2021
     */
    public void setPassScore(String passScore) {
        this.passScore = passScore == null ? null : passScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_exam.remark
     *
     * @return the value of e_exam.remark
     *
     * @mbggenerated Sat Jul 17 22:44:00 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_exam.remark
     *
     * @param remark the value for e_exam.remark
     *
     * @mbggenerated Sat Jul 17 22:44:00 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_exam.feature
     *
     * @return the value of e_exam.feature
     *
     * @mbggenerated Sat Jul 17 22:44:00 CST 2021
     */
    public String getFeature() {
        return feature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_exam.feature
     *
     * @param feature the value for e_exam.feature
     *
     * @mbggenerated Sat Jul 17 22:44:00 CST 2021
     */
    public void setFeature(String feature) {
        this.feature = feature == null ? null : feature.trim();
    }
}