package com.mou.election.dal.domian;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class EmessageDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table e_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table e_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table e_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public EmessageDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table e_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUuidIsNull() {
            addCriterion("uuid is null");
            return (Criteria) this;
        }

        public Criteria andUuidIsNotNull() {
            addCriterion("uuid is not null");
            return (Criteria) this;
        }

        public Criteria andUuidEqualTo(String value) {
            addCriterion("uuid =", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotEqualTo(String value) {
            addCriterion("uuid <>", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThan(String value) {
            addCriterion("uuid >", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThanOrEqualTo(String value) {
            addCriterion("uuid >=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThan(String value) {
            addCriterion("uuid <", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThanOrEqualTo(String value) {
            addCriterion("uuid <=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLike(String value) {
            addCriterion("uuid like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotLike(String value) {
            addCriterion("uuid not like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidIn(List<String> values) {
            addCriterion("uuid in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotIn(List<String> values) {
            addCriterion("uuid not in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidBetween(String value1, String value2) {
            addCriterion("uuid between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotBetween(String value1, String value2) {
            addCriterion("uuid not between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andHeadIsNull() {
            addCriterion("head is null");
            return (Criteria) this;
        }

        public Criteria andHeadIsNotNull() {
            addCriterion("head is not null");
            return (Criteria) this;
        }

        public Criteria andHeadEqualTo(String value) {
            addCriterion("head =", value, "head");
            return (Criteria) this;
        }

        public Criteria andHeadNotEqualTo(String value) {
            addCriterion("head <>", value, "head");
            return (Criteria) this;
        }

        public Criteria andHeadGreaterThan(String value) {
            addCriterion("head >", value, "head");
            return (Criteria) this;
        }

        public Criteria andHeadGreaterThanOrEqualTo(String value) {
            addCriterion("head >=", value, "head");
            return (Criteria) this;
        }

        public Criteria andHeadLessThan(String value) {
            addCriterion("head <", value, "head");
            return (Criteria) this;
        }

        public Criteria andHeadLessThanOrEqualTo(String value) {
            addCriterion("head <=", value, "head");
            return (Criteria) this;
        }

        public Criteria andHeadLike(String value) {
            addCriterion("head like", value, "head");
            return (Criteria) this;
        }

        public Criteria andHeadNotLike(String value) {
            addCriterion("head not like", value, "head");
            return (Criteria) this;
        }

        public Criteria andHeadIn(List<String> values) {
            addCriterion("head in", values, "head");
            return (Criteria) this;
        }

        public Criteria andHeadNotIn(List<String> values) {
            addCriterion("head not in", values, "head");
            return (Criteria) this;
        }

        public Criteria andHeadBetween(String value1, String value2) {
            addCriterion("head between", value1, value2, "head");
            return (Criteria) this;
        }

        public Criteria andHeadNotBetween(String value1, String value2) {
            addCriterion("head not between", value1, value2, "head");
            return (Criteria) this;
        }

        public Criteria andDesctIsNull() {
            addCriterion("desct is null");
            return (Criteria) this;
        }

        public Criteria andDesctIsNotNull() {
            addCriterion("desct is not null");
            return (Criteria) this;
        }

        public Criteria andDesctEqualTo(String value) {
            addCriterion("desct =", value, "desct");
            return (Criteria) this;
        }

        public Criteria andDesctNotEqualTo(String value) {
            addCriterion("desct <>", value, "desct");
            return (Criteria) this;
        }

        public Criteria andDesctGreaterThan(String value) {
            addCriterion("desct >", value, "desct");
            return (Criteria) this;
        }

        public Criteria andDesctGreaterThanOrEqualTo(String value) {
            addCriterion("desct >=", value, "desct");
            return (Criteria) this;
        }

        public Criteria andDesctLessThan(String value) {
            addCriterion("desct <", value, "desct");
            return (Criteria) this;
        }

        public Criteria andDesctLessThanOrEqualTo(String value) {
            addCriterion("desct <=", value, "desct");
            return (Criteria) this;
        }

        public Criteria andDesctLike(String value) {
            addCriterion("desct like", value, "desct");
            return (Criteria) this;
        }

        public Criteria andDesctNotLike(String value) {
            addCriterion("desct not like", value, "desct");
            return (Criteria) this;
        }

        public Criteria andDesctIn(List<String> values) {
            addCriterion("desct in", values, "desct");
            return (Criteria) this;
        }

        public Criteria andDesctNotIn(List<String> values) {
            addCriterion("desct not in", values, "desct");
            return (Criteria) this;
        }

        public Criteria andDesctBetween(String value1, String value2) {
            addCriterion("desct between", value1, value2, "desct");
            return (Criteria) this;
        }

        public Criteria andDesctNotBetween(String value1, String value2) {
            addCriterion("desct not between", value1, value2, "desct");
            return (Criteria) this;
        }

        public Criteria andDetailsIsNull() {
            addCriterion("details is null");
            return (Criteria) this;
        }

        public Criteria andDetailsIsNotNull() {
            addCriterion("details is not null");
            return (Criteria) this;
        }

        public Criteria andDetailsEqualTo(String value) {
            addCriterion("details =", value, "details");
            return (Criteria) this;
        }

        public Criteria andDetailsNotEqualTo(String value) {
            addCriterion("details <>", value, "details");
            return (Criteria) this;
        }

        public Criteria andDetailsGreaterThan(String value) {
            addCriterion("details >", value, "details");
            return (Criteria) this;
        }

        public Criteria andDetailsGreaterThanOrEqualTo(String value) {
            addCriterion("details >=", value, "details");
            return (Criteria) this;
        }

        public Criteria andDetailsLessThan(String value) {
            addCriterion("details <", value, "details");
            return (Criteria) this;
        }

        public Criteria andDetailsLessThanOrEqualTo(String value) {
            addCriterion("details <=", value, "details");
            return (Criteria) this;
        }

        public Criteria andDetailsLike(String value) {
            addCriterion("details like", value, "details");
            return (Criteria) this;
        }

        public Criteria andDetailsNotLike(String value) {
            addCriterion("details not like", value, "details");
            return (Criteria) this;
        }

        public Criteria andDetailsIn(List<String> values) {
            addCriterion("details in", values, "details");
            return (Criteria) this;
        }

        public Criteria andDetailsNotIn(List<String> values) {
            addCriterion("details not in", values, "details");
            return (Criteria) this;
        }

        public Criteria andDetailsBetween(String value1, String value2) {
            addCriterion("details between", value1, value2, "details");
            return (Criteria) this;
        }

        public Criteria andDetailsNotBetween(String value1, String value2) {
            addCriterion("details not between", value1, value2, "details");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andChangeTermDateIsNull() {
            addCriterion("change_term_date is null");
            return (Criteria) this;
        }

        public Criteria andChangeTermDateIsNotNull() {
            addCriterion("change_term_date is not null");
            return (Criteria) this;
        }

        public Criteria andChangeTermDateEqualTo(Date value) {
            addCriterionForJDBCDate("change_term_date =", value, "changeTermDate");
            return (Criteria) this;
        }

        public Criteria andChangeTermDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("change_term_date <>", value, "changeTermDate");
            return (Criteria) this;
        }

        public Criteria andChangeTermDateGreaterThan(Date value) {
            addCriterionForJDBCDate("change_term_date >", value, "changeTermDate");
            return (Criteria) this;
        }

        public Criteria andChangeTermDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("change_term_date >=", value, "changeTermDate");
            return (Criteria) this;
        }

        public Criteria andChangeTermDateLessThan(Date value) {
            addCriterionForJDBCDate("change_term_date <", value, "changeTermDate");
            return (Criteria) this;
        }

        public Criteria andChangeTermDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("change_term_date <=", value, "changeTermDate");
            return (Criteria) this;
        }

        public Criteria andChangeTermDateIn(List<Date> values) {
            addCriterionForJDBCDate("change_term_date in", values, "changeTermDate");
            return (Criteria) this;
        }

        public Criteria andChangeTermDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("change_term_date not in", values, "changeTermDate");
            return (Criteria) this;
        }

        public Criteria andChangeTermDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("change_term_date between", value1, value2, "changeTermDate");
            return (Criteria) this;
        }

        public Criteria andChangeTermDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("change_term_date not between", value1, value2, "changeTermDate");
            return (Criteria) this;
        }

        public Criteria andChangeTermStatusIsNull() {
            addCriterion("change_term_status is null");
            return (Criteria) this;
        }

        public Criteria andChangeTermStatusIsNotNull() {
            addCriterion("change_term_status is not null");
            return (Criteria) this;
        }

        public Criteria andChangeTermStatusEqualTo(Integer value) {
            addCriterion("change_term_status =", value, "changeTermStatus");
            return (Criteria) this;
        }

        public Criteria andChangeTermStatusNotEqualTo(Integer value) {
            addCriterion("change_term_status <>", value, "changeTermStatus");
            return (Criteria) this;
        }

        public Criteria andChangeTermStatusGreaterThan(Integer value) {
            addCriterion("change_term_status >", value, "changeTermStatus");
            return (Criteria) this;
        }

        public Criteria andChangeTermStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("change_term_status >=", value, "changeTermStatus");
            return (Criteria) this;
        }

        public Criteria andChangeTermStatusLessThan(Integer value) {
            addCriterion("change_term_status <", value, "changeTermStatus");
            return (Criteria) this;
        }

        public Criteria andChangeTermStatusLessThanOrEqualTo(Integer value) {
            addCriterion("change_term_status <=", value, "changeTermStatus");
            return (Criteria) this;
        }

        public Criteria andChangeTermStatusIn(List<Integer> values) {
            addCriterion("change_term_status in", values, "changeTermStatus");
            return (Criteria) this;
        }

        public Criteria andChangeTermStatusNotIn(List<Integer> values) {
            addCriterion("change_term_status not in", values, "changeTermStatus");
            return (Criteria) this;
        }

        public Criteria andChangeTermStatusBetween(Integer value1, Integer value2) {
            addCriterion("change_term_status between", value1, value2, "changeTermStatus");
            return (Criteria) this;
        }

        public Criteria andChangeTermStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("change_term_status not between", value1, value2, "changeTermStatus");
            return (Criteria) this;
        }

        public Criteria andIsChangeTermIsNull() {
            addCriterion("is_change_term is null");
            return (Criteria) this;
        }

        public Criteria andIsChangeTermIsNotNull() {
            addCriterion("is_change_term is not null");
            return (Criteria) this;
        }

        public Criteria andIsChangeTermEqualTo(String value) {
            addCriterion("is_change_term =", value, "isChangeTerm");
            return (Criteria) this;
        }

        public Criteria andIsChangeTermNotEqualTo(String value) {
            addCriterion("is_change_term <>", value, "isChangeTerm");
            return (Criteria) this;
        }

        public Criteria andIsChangeTermGreaterThan(String value) {
            addCriterion("is_change_term >", value, "isChangeTerm");
            return (Criteria) this;
        }

        public Criteria andIsChangeTermGreaterThanOrEqualTo(String value) {
            addCriterion("is_change_term >=", value, "isChangeTerm");
            return (Criteria) this;
        }

        public Criteria andIsChangeTermLessThan(String value) {
            addCriterion("is_change_term <", value, "isChangeTerm");
            return (Criteria) this;
        }

        public Criteria andIsChangeTermLessThanOrEqualTo(String value) {
            addCriterion("is_change_term <=", value, "isChangeTerm");
            return (Criteria) this;
        }

        public Criteria andIsChangeTermLike(String value) {
            addCriterion("is_change_term like", value, "isChangeTerm");
            return (Criteria) this;
        }

        public Criteria andIsChangeTermNotLike(String value) {
            addCriterion("is_change_term not like", value, "isChangeTerm");
            return (Criteria) this;
        }

        public Criteria andIsChangeTermIn(List<String> values) {
            addCriterion("is_change_term in", values, "isChangeTerm");
            return (Criteria) this;
        }

        public Criteria andIsChangeTermNotIn(List<String> values) {
            addCriterion("is_change_term not in", values, "isChangeTerm");
            return (Criteria) this;
        }

        public Criteria andIsChangeTermBetween(String value1, String value2) {
            addCriterion("is_change_term between", value1, value2, "isChangeTerm");
            return (Criteria) this;
        }

        public Criteria andIsChangeTermNotBetween(String value1, String value2) {
            addCriterion("is_change_term not between", value1, value2, "isChangeTerm");
            return (Criteria) this;
        }

        public Criteria andIsDetailsIsNull() {
            addCriterion("is_details is null");
            return (Criteria) this;
        }

        public Criteria andIsDetailsIsNotNull() {
            addCriterion("is_details is not null");
            return (Criteria) this;
        }

        public Criteria andIsDetailsEqualTo(String value) {
            addCriterion("is_details =", value, "isDetails");
            return (Criteria) this;
        }

        public Criteria andIsDetailsNotEqualTo(String value) {
            addCriterion("is_details <>", value, "isDetails");
            return (Criteria) this;
        }

        public Criteria andIsDetailsGreaterThan(String value) {
            addCriterion("is_details >", value, "isDetails");
            return (Criteria) this;
        }

        public Criteria andIsDetailsGreaterThanOrEqualTo(String value) {
            addCriterion("is_details >=", value, "isDetails");
            return (Criteria) this;
        }

        public Criteria andIsDetailsLessThan(String value) {
            addCriterion("is_details <", value, "isDetails");
            return (Criteria) this;
        }

        public Criteria andIsDetailsLessThanOrEqualTo(String value) {
            addCriterion("is_details <=", value, "isDetails");
            return (Criteria) this;
        }

        public Criteria andIsDetailsLike(String value) {
            addCriterion("is_details like", value, "isDetails");
            return (Criteria) this;
        }

        public Criteria andIsDetailsNotLike(String value) {
            addCriterion("is_details not like", value, "isDetails");
            return (Criteria) this;
        }

        public Criteria andIsDetailsIn(List<String> values) {
            addCriterion("is_details in", values, "isDetails");
            return (Criteria) this;
        }

        public Criteria andIsDetailsNotIn(List<String> values) {
            addCriterion("is_details not in", values, "isDetails");
            return (Criteria) this;
        }

        public Criteria andIsDetailsBetween(String value1, String value2) {
            addCriterion("is_details between", value1, value2, "isDetails");
            return (Criteria) this;
        }

        public Criteria andIsDetailsNotBetween(String value1, String value2) {
            addCriterion("is_details not between", value1, value2, "isDetails");
            return (Criteria) this;
        }

        public Criteria andIsPopupIsNull() {
            addCriterion("is_popup is null");
            return (Criteria) this;
        }

        public Criteria andIsPopupIsNotNull() {
            addCriterion("is_popup is not null");
            return (Criteria) this;
        }

        public Criteria andIsPopupEqualTo(String value) {
            addCriterion("is_popup =", value, "isPopup");
            return (Criteria) this;
        }

        public Criteria andIsPopupNotEqualTo(String value) {
            addCriterion("is_popup <>", value, "isPopup");
            return (Criteria) this;
        }

        public Criteria andIsPopupGreaterThan(String value) {
            addCriterion("is_popup >", value, "isPopup");
            return (Criteria) this;
        }

        public Criteria andIsPopupGreaterThanOrEqualTo(String value) {
            addCriterion("is_popup >=", value, "isPopup");
            return (Criteria) this;
        }

        public Criteria andIsPopupLessThan(String value) {
            addCriterion("is_popup <", value, "isPopup");
            return (Criteria) this;
        }

        public Criteria andIsPopupLessThanOrEqualTo(String value) {
            addCriterion("is_popup <=", value, "isPopup");
            return (Criteria) this;
        }

        public Criteria andIsPopupLike(String value) {
            addCriterion("is_popup like", value, "isPopup");
            return (Criteria) this;
        }

        public Criteria andIsPopupNotLike(String value) {
            addCriterion("is_popup not like", value, "isPopup");
            return (Criteria) this;
        }

        public Criteria andIsPopupIn(List<String> values) {
            addCriterion("is_popup in", values, "isPopup");
            return (Criteria) this;
        }

        public Criteria andIsPopupNotIn(List<String> values) {
            addCriterion("is_popup not in", values, "isPopup");
            return (Criteria) this;
        }

        public Criteria andIsPopupBetween(String value1, String value2) {
            addCriterion("is_popup between", value1, value2, "isPopup");
            return (Criteria) this;
        }

        public Criteria andIsPopupNotBetween(String value1, String value2) {
            addCriterion("is_popup not between", value1, value2, "isPopup");
            return (Criteria) this;
        }

        public Criteria andIsReceiptIsNull() {
            addCriterion("is_receipt is null");
            return (Criteria) this;
        }

        public Criteria andIsReceiptIsNotNull() {
            addCriterion("is_receipt is not null");
            return (Criteria) this;
        }

        public Criteria andIsReceiptEqualTo(String value) {
            addCriterion("is_receipt =", value, "isReceipt");
            return (Criteria) this;
        }

        public Criteria andIsReceiptNotEqualTo(String value) {
            addCriterion("is_receipt <>", value, "isReceipt");
            return (Criteria) this;
        }

        public Criteria andIsReceiptGreaterThan(String value) {
            addCriterion("is_receipt >", value, "isReceipt");
            return (Criteria) this;
        }

        public Criteria andIsReceiptGreaterThanOrEqualTo(String value) {
            addCriterion("is_receipt >=", value, "isReceipt");
            return (Criteria) this;
        }

        public Criteria andIsReceiptLessThan(String value) {
            addCriterion("is_receipt <", value, "isReceipt");
            return (Criteria) this;
        }

        public Criteria andIsReceiptLessThanOrEqualTo(String value) {
            addCriterion("is_receipt <=", value, "isReceipt");
            return (Criteria) this;
        }

        public Criteria andIsReceiptLike(String value) {
            addCriterion("is_receipt like", value, "isReceipt");
            return (Criteria) this;
        }

        public Criteria andIsReceiptNotLike(String value) {
            addCriterion("is_receipt not like", value, "isReceipt");
            return (Criteria) this;
        }

        public Criteria andIsReceiptIn(List<String> values) {
            addCriterion("is_receipt in", values, "isReceipt");
            return (Criteria) this;
        }

        public Criteria andIsReceiptNotIn(List<String> values) {
            addCriterion("is_receipt not in", values, "isReceipt");
            return (Criteria) this;
        }

        public Criteria andIsReceiptBetween(String value1, String value2) {
            addCriterion("is_receipt between", value1, value2, "isReceipt");
            return (Criteria) this;
        }

        public Criteria andIsReceiptNotBetween(String value1, String value2) {
            addCriterion("is_receipt not between", value1, value2, "isReceipt");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("create_user like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("create_user not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNull() {
            addCriterion("last_update_time is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNotNull() {
            addCriterion("last_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeEqualTo(Date value) {
            addCriterion("last_update_time =", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotEqualTo(Date value) {
            addCriterion("last_update_time <>", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThan(Date value) {
            addCriterion("last_update_time >", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_update_time >=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThan(Date value) {
            addCriterion("last_update_time <", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_update_time <=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIn(List<Date> values) {
            addCriterion("last_update_time in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotIn(List<Date> values) {
            addCriterion("last_update_time not in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("last_update_time between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_update_time not between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserIsNull() {
            addCriterion("last_update_user is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserIsNotNull() {
            addCriterion("last_update_user is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserEqualTo(String value) {
            addCriterion("last_update_user =", value, "lastUpdateUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserNotEqualTo(String value) {
            addCriterion("last_update_user <>", value, "lastUpdateUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserGreaterThan(String value) {
            addCriterion("last_update_user >", value, "lastUpdateUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("last_update_user >=", value, "lastUpdateUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserLessThan(String value) {
            addCriterion("last_update_user <", value, "lastUpdateUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("last_update_user <=", value, "lastUpdateUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserLike(String value) {
            addCriterion("last_update_user like", value, "lastUpdateUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserNotLike(String value) {
            addCriterion("last_update_user not like", value, "lastUpdateUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserIn(List<String> values) {
            addCriterion("last_update_user in", values, "lastUpdateUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserNotIn(List<String> values) {
            addCriterion("last_update_user not in", values, "lastUpdateUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserBetween(String value1, String value2) {
            addCriterion("last_update_user between", value1, value2, "lastUpdateUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserNotBetween(String value1, String value2) {
            addCriterion("last_update_user not between", value1, value2, "lastUpdateUser");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table e_message
     *
     * @mbggenerated do_not_delete_during_merge Tue Jul 06 08:37:32 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table e_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}