package com.mou.election.dal.domian;

import java.util.Date;

public class EmessageDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_message.id
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_message.uuid
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_message.head
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    private String head;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_message.desct
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    private String desct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_message.details
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    private String details;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_message.status
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_message.type
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_message.change_term_date
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    private Date changeTermDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_message.change_term_status
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    private Integer changeTermStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_message.is_change_term
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    private String isChangeTerm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_message.is_details
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    private String isDetails;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_message.is_popup
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    private String isPopup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_message.is_receipt
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    private String isReceipt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_message.create_time
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_message.create_user
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_message.last_update_time
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_message.last_update_user
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    private String lastUpdateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_message.id
     *
     * @return the value of e_message.id
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_message.id
     *
     * @param id the value for e_message.id
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_message.uuid
     *
     * @return the value of e_message.uuid
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_message.uuid
     *
     * @param uuid the value for e_message.uuid
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_message.head
     *
     * @return the value of e_message.head
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public String getHead() {
        return head;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_message.head
     *
     * @param head the value for e_message.head
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public void setHead(String head) {
        this.head = head == null ? null : head.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_message.desct
     *
     * @return the value of e_message.desct
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public String getDesct() {
        return desct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_message.desct
     *
     * @param desct the value for e_message.desct
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public void setDesct(String desct) {
        this.desct = desct == null ? null : desct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_message.details
     *
     * @return the value of e_message.details
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_message.details
     *
     * @param details the value for e_message.details
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public void setDetails(String details) {
        this.details = details == null ? null : details.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_message.status
     *
     * @return the value of e_message.status
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_message.status
     *
     * @param status the value for e_message.status
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_message.type
     *
     * @return the value of e_message.type
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_message.type
     *
     * @param type the value for e_message.type
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_message.change_term_date
     *
     * @return the value of e_message.change_term_date
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public Date getChangeTermDate() {
        return changeTermDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_message.change_term_date
     *
     * @param changeTermDate the value for e_message.change_term_date
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public void setChangeTermDate(Date changeTermDate) {
        this.changeTermDate = changeTermDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_message.change_term_status
     *
     * @return the value of e_message.change_term_status
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public Integer getChangeTermStatus() {
        return changeTermStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_message.change_term_status
     *
     * @param changeTermStatus the value for e_message.change_term_status
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public void setChangeTermStatus(Integer changeTermStatus) {
        this.changeTermStatus = changeTermStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_message.is_change_term
     *
     * @return the value of e_message.is_change_term
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public String getIsChangeTerm() {
        return isChangeTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_message.is_change_term
     *
     * @param isChangeTerm the value for e_message.is_change_term
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public void setIsChangeTerm(String isChangeTerm) {
        this.isChangeTerm = isChangeTerm == null ? null : isChangeTerm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_message.is_details
     *
     * @return the value of e_message.is_details
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public String getIsDetails() {
        return isDetails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_message.is_details
     *
     * @param isDetails the value for e_message.is_details
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public void setIsDetails(String isDetails) {
        this.isDetails = isDetails == null ? null : isDetails.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_message.is_popup
     *
     * @return the value of e_message.is_popup
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public String getIsPopup() {
        return isPopup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_message.is_popup
     *
     * @param isPopup the value for e_message.is_popup
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public void setIsPopup(String isPopup) {
        this.isPopup = isPopup == null ? null : isPopup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_message.is_receipt
     *
     * @return the value of e_message.is_receipt
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public String getIsReceipt() {
        return isReceipt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_message.is_receipt
     *
     * @param isReceipt the value for e_message.is_receipt
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public void setIsReceipt(String isReceipt) {
        this.isReceipt = isReceipt == null ? null : isReceipt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_message.create_time
     *
     * @return the value of e_message.create_time
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_message.create_time
     *
     * @param createTime the value for e_message.create_time
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_message.create_user
     *
     * @return the value of e_message.create_user
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_message.create_user
     *
     * @param createUser the value for e_message.create_user
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_message.last_update_time
     *
     * @return the value of e_message.last_update_time
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_message.last_update_time
     *
     * @param lastUpdateTime the value for e_message.last_update_time
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_message.last_update_user
     *
     * @return the value of e_message.last_update_user
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public String getLastUpdateUser() {
        return lastUpdateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_message.last_update_user
     *
     * @param lastUpdateUser the value for e_message.last_update_user
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public void setLastUpdateUser(String lastUpdateUser) {
        this.lastUpdateUser = lastUpdateUser == null ? null : lastUpdateUser.trim();
    }
}