package com.mou.election.dal.domian;

import java.util.Date;

public class EmessageTypeDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_message_type.id
     *
     * @mbggenerated Sat Jul 03 20:36:15 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_message_type.type_desc
     *
     * @mbggenerated Sat Jul 03 20:36:15 CST 2021
     */
    private String typeDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_message_type.type_parent_id
     *
     * @mbggenerated Sat Jul 03 20:36:15 CST 2021
     */
    private Integer typeParentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_message_type.create_time
     *
     * @mbggenerated Sat Jul 03 20:36:15 CST 2021
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_message_type.create_user
     *
     * @mbggenerated Sat Jul 03 20:36:15 CST 2021
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_message_type.last_update_time
     *
     * @mbggenerated Sat Jul 03 20:36:15 CST 2021
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_message_type.last_update_user
     *
     * @mbggenerated Sat Jul 03 20:36:15 CST 2021
     */
    private String lastUpdateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_message_type.id
     *
     * @return the value of e_message_type.id
     *
     * @mbggenerated Sat Jul 03 20:36:15 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_message_type.id
     *
     * @param id the value for e_message_type.id
     *
     * @mbggenerated Sat Jul 03 20:36:15 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_message_type.type_desc
     *
     * @return the value of e_message_type.type_desc
     *
     * @mbggenerated Sat Jul 03 20:36:15 CST 2021
     */
    public String getTypeDesc() {
        return typeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_message_type.type_desc
     *
     * @param typeDesc the value for e_message_type.type_desc
     *
     * @mbggenerated Sat Jul 03 20:36:15 CST 2021
     */
    public void setTypeDesc(String typeDesc) {
        this.typeDesc = typeDesc == null ? null : typeDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_message_type.type_parent_id
     *
     * @return the value of e_message_type.type_parent_id
     *
     * @mbggenerated Sat Jul 03 20:36:15 CST 2021
     */
    public Integer getTypeParentId() {
        return typeParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_message_type.type_parent_id
     *
     * @param typeParentId the value for e_message_type.type_parent_id
     *
     * @mbggenerated Sat Jul 03 20:36:15 CST 2021
     */
    public void setTypeParentId(Integer typeParentId) {
        this.typeParentId = typeParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_message_type.create_time
     *
     * @return the value of e_message_type.create_time
     *
     * @mbggenerated Sat Jul 03 20:36:15 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_message_type.create_time
     *
     * @param createTime the value for e_message_type.create_time
     *
     * @mbggenerated Sat Jul 03 20:36:15 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_message_type.create_user
     *
     * @return the value of e_message_type.create_user
     *
     * @mbggenerated Sat Jul 03 20:36:15 CST 2021
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_message_type.create_user
     *
     * @param createUser the value for e_message_type.create_user
     *
     * @mbggenerated Sat Jul 03 20:36:15 CST 2021
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_message_type.last_update_time
     *
     * @return the value of e_message_type.last_update_time
     *
     * @mbggenerated Sat Jul 03 20:36:15 CST 2021
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_message_type.last_update_time
     *
     * @param lastUpdateTime the value for e_message_type.last_update_time
     *
     * @mbggenerated Sat Jul 03 20:36:15 CST 2021
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_message_type.last_update_user
     *
     * @return the value of e_message_type.last_update_user
     *
     * @mbggenerated Sat Jul 03 20:36:15 CST 2021
     */
    public String getLastUpdateUser() {
        return lastUpdateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_message_type.last_update_user
     *
     * @param lastUpdateUser the value for e_message_type.last_update_user
     *
     * @mbggenerated Sat Jul 03 20:36:15 CST 2021
     */
    public void setLastUpdateUser(String lastUpdateUser) {
        this.lastUpdateUser = lastUpdateUser == null ? null : lastUpdateUser.trim();
    }
}