package com.mou.election.dal.domian;

import java.util.Date;

public class EorganizationDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_organization.id
     *
     * @mbggenerated Sun Jul 04 10:34:34 CST 2021
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_organization.gmt_create
     *
     * @mbggenerated Sun Jul 04 10:34:34 CST 2021
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_organization.gmt_modified
     *
     * @mbggenerated Sun Jul 04 10:34:34 CST 2021
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_organization.organization_name
     *
     * @mbggenerated Sun Jul 04 10:34:34 CST 2021
     */
    private String organizationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_organization.feature
     *
     * @mbggenerated Sun Jul 04 10:34:34 CST 2021
     */
    private String feature;

    private Date changeTermTime;

    private String sendStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_organization.id
     *
     * @return the value of e_organization.id
     *
     * @mbggenerated Sun Jul 04 10:34:34 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_organization.id
     *
     * @param id the value for e_organization.id
     *
     * @mbggenerated Sun Jul 04 10:34:34 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_organization.gmt_create
     *
     * @return the value of e_organization.gmt_create
     *
     * @mbggenerated Sun Jul 04 10:34:34 CST 2021
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_organization.gmt_create
     *
     * @param gmtCreate the value for e_organization.gmt_create
     *
     * @mbggenerated Sun Jul 04 10:34:34 CST 2021
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_organization.gmt_modified
     *
     * @return the value of e_organization.gmt_modified
     *
     * @mbggenerated Sun Jul 04 10:34:34 CST 2021
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_organization.gmt_modified
     *
     * @param gmtModified the value for e_organization.gmt_modified
     *
     * @mbggenerated Sun Jul 04 10:34:34 CST 2021
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_organization.organization_name
     *
     * @return the value of e_organization.organization_name
     *
     * @mbggenerated Sun Jul 04 10:34:34 CST 2021
     */
    public String getOrganizationName() {
        return organizationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_organization.organization_name
     *
     * @param organizationName the value for e_organization.organization_name
     *
     * @mbggenerated Sun Jul 04 10:34:34 CST 2021
     */
    public void setOrganizationName(String organizationName) {
        this.organizationName = organizationName == null ? null : organizationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_organization.feature
     *
     * @return the value of e_organization.feature
     *
     * @mbggenerated Sun Jul 04 10:34:34 CST 2021
     */
    public String getFeature() {
        return feature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_organization.feature
     *
     * @param feature the value for e_organization.feature
     *
     * @mbggenerated Sun Jul 04 10:34:34 CST 2021
     */
    public void setFeature(String feature) {
        this.feature = feature == null ? null : feature.trim();
    }

    public Date getChangeTermTime() {
        return changeTermTime;
    }

    public void setChangeTermTime(Date changeTermTime) {
        this.changeTermTime = changeTermTime;
    }

    public String getSendStatus() {
        return sendStatus;
    }

    public void setSendStatus(String sendStatus) {
        this.sendStatus = sendStatus;
    }
}