package com.mou.election.dal.domian;

import java.util.Date;

public class EpermissionDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_permission.id
     *
     * @mbggenerated Wed Jul 07 01:00:38 CST 2021
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_permission.gmt_create
     *
     * @mbggenerated Wed Jul 07 01:00:38 CST 2021
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_permission.gmt_modified
     *
     * @mbggenerated Wed Jul 07 01:00:38 CST 2021
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_permission.permission_name
     *
     * @mbggenerated Wed Jul 07 01:00:38 CST 2021
     */
    private String permissionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_permission.feature
     *
     * @mbggenerated Wed Jul 07 01:00:38 CST 2021
     */
    private String feature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_permission.permission_code
     *
     * @mbggenerated Wed Jul 07 01:00:38 CST 2021
     */
    private String permissionCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_permission.id
     *
     * @return the value of e_permission.id
     *
     * @mbggenerated Wed Jul 07 01:00:38 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_permission.id
     *
     * @param id the value for e_permission.id
     *
     * @mbggenerated Wed Jul 07 01:00:38 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_permission.gmt_create
     *
     * @return the value of e_permission.gmt_create
     *
     * @mbggenerated Wed Jul 07 01:00:38 CST 2021
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_permission.gmt_create
     *
     * @param gmtCreate the value for e_permission.gmt_create
     *
     * @mbggenerated Wed Jul 07 01:00:38 CST 2021
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_permission.gmt_modified
     *
     * @return the value of e_permission.gmt_modified
     *
     * @mbggenerated Wed Jul 07 01:00:38 CST 2021
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_permission.gmt_modified
     *
     * @param gmtModified the value for e_permission.gmt_modified
     *
     * @mbggenerated Wed Jul 07 01:00:38 CST 2021
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_permission.permission_name
     *
     * @return the value of e_permission.permission_name
     *
     * @mbggenerated Wed Jul 07 01:00:38 CST 2021
     */
    public String getPermissionName() {
        return permissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_permission.permission_name
     *
     * @param permissionName the value for e_permission.permission_name
     *
     * @mbggenerated Wed Jul 07 01:00:38 CST 2021
     */
    public void setPermissionName(String permissionName) {
        this.permissionName = permissionName == null ? null : permissionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_permission.feature
     *
     * @return the value of e_permission.feature
     *
     * @mbggenerated Wed Jul 07 01:00:38 CST 2021
     */
    public String getFeature() {
        return feature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_permission.feature
     *
     * @param feature the value for e_permission.feature
     *
     * @mbggenerated Wed Jul 07 01:00:38 CST 2021
     */
    public void setFeature(String feature) {
        this.feature = feature == null ? null : feature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_permission.permission_code
     *
     * @return the value of e_permission.permission_code
     *
     * @mbggenerated Wed Jul 07 01:00:38 CST 2021
     */
    public String getPermissionCode() {
        return permissionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_permission.permission_code
     *
     * @param permissionCode the value for e_permission.permission_code
     *
     * @mbggenerated Wed Jul 07 01:00:38 CST 2021
     */
    public void setPermissionCode(String permissionCode) {
        this.permissionCode = permissionCode == null ? null : permissionCode.trim();
    }
}