package com.mou.election.dal.domian;

import java.util.Date;

public class EQuestionDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_question.id
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_question.gmt_create
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_question.gmt_modified
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_question.title
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_question.type
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_question.sort
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_question.exam_id
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    private Long examId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_question.score
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_question.id
     *
     * @return the value of e_question.id
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_question.id
     *
     * @param id the value for e_question.id
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_question.gmt_create
     *
     * @return the value of e_question.gmt_create
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_question.gmt_create
     *
     * @param gmtCreate the value for e_question.gmt_create
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_question.gmt_modified
     *
     * @return the value of e_question.gmt_modified
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_question.gmt_modified
     *
     * @param gmtModified the value for e_question.gmt_modified
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_question.title
     *
     * @return the value of e_question.title
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_question.title
     *
     * @param title the value for e_question.title
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_question.type
     *
     * @return the value of e_question.type
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_question.type
     *
     * @param type the value for e_question.type
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_question.sort
     *
     * @return the value of e_question.sort
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_question.sort
     *
     * @param sort the value for e_question.sort
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_question.exam_id
     *
     * @return the value of e_question.exam_id
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    public Long getExamId() {
        return examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_question.exam_id
     *
     * @param examId the value for e_question.exam_id
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    public void setExamId(Long examId) {
        this.examId = examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_question.score
     *
     * @return the value of e_question.score
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_question.score
     *
     * @param score the value for e_question.score
     *
     * @mbggenerated Sat Jul 17 00:43:51 CST 2021
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}