package com.mou.election.dal.domian;

import java.util.Date;

public class EroleDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_role.id
     *
     * @mbggenerated Wed Jul 07 02:05:19 CST 2021
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_role.gmt_create
     *
     * @mbggenerated Wed Jul 07 02:05:19 CST 2021
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_role.gmt_modified
     *
     * @mbggenerated Wed Jul 07 02:05:19 CST 2021
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_role.role_name
     *
     * @mbggenerated Wed Jul 07 02:05:19 CST 2021
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_role.feature
     *
     * @mbggenerated Wed Jul 07 02:05:19 CST 2021
     */
    private String feature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_role.role_code
     *
     * @mbggenerated Wed Jul 07 02:05:19 CST 2021
     */
    private String roleCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_role.id
     *
     * @return the value of e_role.id
     *
     * @mbggenerated Wed Jul 07 02:05:19 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_role.id
     *
     * @param id the value for e_role.id
     *
     * @mbggenerated Wed Jul 07 02:05:19 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_role.gmt_create
     *
     * @return the value of e_role.gmt_create
     *
     * @mbggenerated Wed Jul 07 02:05:19 CST 2021
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_role.gmt_create
     *
     * @param gmtCreate the value for e_role.gmt_create
     *
     * @mbggenerated Wed Jul 07 02:05:19 CST 2021
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_role.gmt_modified
     *
     * @return the value of e_role.gmt_modified
     *
     * @mbggenerated Wed Jul 07 02:05:19 CST 2021
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_role.gmt_modified
     *
     * @param gmtModified the value for e_role.gmt_modified
     *
     * @mbggenerated Wed Jul 07 02:05:19 CST 2021
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_role.role_name
     *
     * @return the value of e_role.role_name
     *
     * @mbggenerated Wed Jul 07 02:05:19 CST 2021
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_role.role_name
     *
     * @param roleName the value for e_role.role_name
     *
     * @mbggenerated Wed Jul 07 02:05:19 CST 2021
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_role.feature
     *
     * @return the value of e_role.feature
     *
     * @mbggenerated Wed Jul 07 02:05:19 CST 2021
     */
    public String getFeature() {
        return feature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_role.feature
     *
     * @param feature the value for e_role.feature
     *
     * @mbggenerated Wed Jul 07 02:05:19 CST 2021
     */
    public void setFeature(String feature) {
        this.feature = feature == null ? null : feature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_role.role_code
     *
     * @return the value of e_role.role_code
     *
     * @mbggenerated Wed Jul 07 02:05:19 CST 2021
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_role.role_code
     *
     * @param roleCode the value for e_role.role_code
     *
     * @mbggenerated Wed Jul 07 02:05:19 CST 2021
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode == null ? null : roleCode.trim();
    }
}