package com.mou.election.dal.domian;

import java.util.Date;

public class EuserMessageDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user_message.id
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user_message.message_id
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    private String messageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user_message.user_attr
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    private String userAttr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user_message.is_receipt
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    private String isReceipt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user_message.is_change_term
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    private String isChangeTerm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user_message.message_reply_status
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    private Integer messageReplyStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user_message.popup_status
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    private Integer popupStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user_message.create_time
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user_message.last_update_time
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    private Date lastUpdateTime;

    private Integer readStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user_message.id
     *
     * @return the value of e_user_message.id
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user_message.id
     *
     * @param id the value for e_user_message.id
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user_message.message_id
     *
     * @return the value of e_user_message.message_id
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public String getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user_message.message_id
     *
     * @param messageId the value for e_user_message.message_id
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public void setMessageId(String messageId) {
        this.messageId = messageId == null ? null : messageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user_message.user_attr
     *
     * @return the value of e_user_message.user_attr
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public String getUserAttr() {
        return userAttr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user_message.user_attr
     *
     * @param userAttr the value for e_user_message.user_attr
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public void setUserAttr(String userAttr) {
        this.userAttr = userAttr == null ? null : userAttr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user_message.is_receipt
     *
     * @return the value of e_user_message.is_receipt
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public String getIsReceipt() {
        return isReceipt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user_message.is_receipt
     *
     * @param isReceipt the value for e_user_message.is_receipt
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public void setIsReceipt(String isReceipt) {
        this.isReceipt = isReceipt == null ? null : isReceipt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user_message.is_change_term
     *
     * @return the value of e_user_message.is_change_term
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public String getIsChangeTerm() {
        return isChangeTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user_message.is_change_term
     *
     * @param isChangeTerm the value for e_user_message.is_change_term
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public void setIsChangeTerm(String isChangeTerm) {
        this.isChangeTerm = isChangeTerm == null ? null : isChangeTerm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user_message.message_reply_status
     *
     * @return the value of e_user_message.message_reply_status
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public Integer getMessageReplyStatus() {
        return messageReplyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user_message.message_reply_status
     *
     * @param messageReplyStatus the value for e_user_message.message_reply_status
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public void setMessageReplyStatus(Integer messageReplyStatus) {
        this.messageReplyStatus = messageReplyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user_message.popup_status
     *
     * @return the value of e_user_message.popup_status
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public Integer getPopupStatus() {
        return popupStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user_message.popup_status
     *
     * @param popupStatus the value for e_user_message.popup_status
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public void setPopupStatus(Integer popupStatus) {
        this.popupStatus = popupStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user_message.create_time
     *
     * @return the value of e_user_message.create_time
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user_message.create_time
     *
     * @param createTime the value for e_user_message.create_time
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user_message.last_update_time
     *
     * @return the value of e_user_message.last_update_time
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user_message.last_update_time
     *
     * @param lastUpdateTime the value for e_user_message.last_update_time
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    public Integer getReadStatus() {
        return readStatus;
    }

    public void setReadStatus(Integer readStatus) {
        this.readStatus = readStatus;
    }
}