package com.mou.election.dal.domian;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class EuserMessageDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table e_user_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table e_user_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table e_user_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_user_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public EuserMessageDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_user_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_user_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_user_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_user_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_user_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_user_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_user_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_user_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_user_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_user_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table e_user_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMessageIdIsNull() {
            addCriterion("message_id is null");
            return (Criteria) this;
        }

        public Criteria andMessageIdIsNotNull() {
            addCriterion("message_id is not null");
            return (Criteria) this;
        }

        public Criteria andMessageIdEqualTo(String value) {
            addCriterion("message_id =", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdNotEqualTo(String value) {
            addCriterion("message_id <>", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdGreaterThan(String value) {
            addCriterion("message_id >", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdGreaterThanOrEqualTo(String value) {
            addCriterion("message_id >=", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdLessThan(String value) {
            addCriterion("message_id <", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdLessThanOrEqualTo(String value) {
            addCriterion("message_id <=", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdLike(String value) {
            addCriterion("message_id like", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdNotLike(String value) {
            addCriterion("message_id not like", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdIn(List<String> values) {
            addCriterion("message_id in", values, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdNotIn(List<String> values) {
            addCriterion("message_id not in", values, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdBetween(String value1, String value2) {
            addCriterion("message_id between", value1, value2, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdNotBetween(String value1, String value2) {
            addCriterion("message_id not between", value1, value2, "messageId");
            return (Criteria) this;
        }

        public Criteria andUserAttrIsNull() {
            addCriterion("user_attr is null");
            return (Criteria) this;
        }

        public Criteria andUserAttrIsNotNull() {
            addCriterion("user_attr is not null");
            return (Criteria) this;
        }

        public Criteria andUserAttrEqualTo(String value) {
            addCriterion("user_attr =", value, "userAttr");
            return (Criteria) this;
        }

        public Criteria andUserAttrNotEqualTo(String value) {
            addCriterion("user_attr <>", value, "userAttr");
            return (Criteria) this;
        }

        public Criteria andUserAttrGreaterThan(String value) {
            addCriterion("user_attr >", value, "userAttr");
            return (Criteria) this;
        }

        public Criteria andUserAttrGreaterThanOrEqualTo(String value) {
            addCriterion("user_attr >=", value, "userAttr");
            return (Criteria) this;
        }

        public Criteria andUserAttrLessThan(String value) {
            addCriterion("user_attr <", value, "userAttr");
            return (Criteria) this;
        }

        public Criteria andUserAttrLessThanOrEqualTo(String value) {
            addCriterion("user_attr <=", value, "userAttr");
            return (Criteria) this;
        }

        public Criteria andUserAttrLike(String value) {
            addCriterion("user_attr like", value, "userAttr");
            return (Criteria) this;
        }

        public Criteria andUserAttrNotLike(String value) {
            addCriterion("user_attr not like", value, "userAttr");
            return (Criteria) this;
        }

        public Criteria andUserAttrIn(List<String> values) {
            addCriterion("user_attr in", values, "userAttr");
            return (Criteria) this;
        }

        public Criteria andUserAttrNotIn(List<String> values) {
            addCriterion("user_attr not in", values, "userAttr");
            return (Criteria) this;
        }

        public Criteria andUserAttrBetween(String value1, String value2) {
            addCriterion("user_attr between", value1, value2, "userAttr");
            return (Criteria) this;
        }

        public Criteria andUserAttrNotBetween(String value1, String value2) {
            addCriterion("user_attr not between", value1, value2, "userAttr");
            return (Criteria) this;
        }

        public Criteria andIsReceiptIsNull() {
            addCriterion("is_receipt is null");
            return (Criteria) this;
        }

        public Criteria andIsReceiptIsNotNull() {
            addCriterion("is_receipt is not null");
            return (Criteria) this;
        }

        public Criteria andIsReceiptEqualTo(String value) {
            addCriterion("is_receipt =", value, "isReceipt");
            return (Criteria) this;
        }

        public Criteria andIsReceiptNotEqualTo(String value) {
            addCriterion("is_receipt <>", value, "isReceipt");
            return (Criteria) this;
        }

        public Criteria andIsReceiptGreaterThan(String value) {
            addCriterion("is_receipt >", value, "isReceipt");
            return (Criteria) this;
        }

        public Criteria andIsReceiptGreaterThanOrEqualTo(String value) {
            addCriterion("is_receipt >=", value, "isReceipt");
            return (Criteria) this;
        }

        public Criteria andIsReceiptLessThan(String value) {
            addCriterion("is_receipt <", value, "isReceipt");
            return (Criteria) this;
        }

        public Criteria andIsReceiptLessThanOrEqualTo(String value) {
            addCriterion("is_receipt <=", value, "isReceipt");
            return (Criteria) this;
        }

        public Criteria andIsReceiptLike(String value) {
            addCriterion("is_receipt like", value, "isReceipt");
            return (Criteria) this;
        }

        public Criteria andIsReceiptNotLike(String value) {
            addCriterion("is_receipt not like", value, "isReceipt");
            return (Criteria) this;
        }

        public Criteria andIsReceiptIn(List<String> values) {
            addCriterion("is_receipt in", values, "isReceipt");
            return (Criteria) this;
        }

        public Criteria andIsReceiptNotIn(List<String> values) {
            addCriterion("is_receipt not in", values, "isReceipt");
            return (Criteria) this;
        }

        public Criteria andIsReceiptBetween(String value1, String value2) {
            addCriterion("is_receipt between", value1, value2, "isReceipt");
            return (Criteria) this;
        }

        public Criteria andIsReceiptNotBetween(String value1, String value2) {
            addCriterion("is_receipt not between", value1, value2, "isReceipt");
            return (Criteria) this;
        }

        public Criteria andIsChangeTermIsNull() {
            addCriterion("is_change_term is null");
            return (Criteria) this;
        }

        public Criteria andIsChangeTermIsNotNull() {
            addCriterion("is_change_term is not null");
            return (Criteria) this;
        }

        public Criteria andIsChangeTermEqualTo(String value) {
            addCriterion("is_change_term =", value, "isChangeTerm");
            return (Criteria) this;
        }

        public Criteria andIsChangeTermNotEqualTo(String value) {
            addCriterion("is_change_term <>", value, "isChangeTerm");
            return (Criteria) this;
        }

        public Criteria andIsChangeTermGreaterThan(String value) {
            addCriterion("is_change_term >", value, "isChangeTerm");
            return (Criteria) this;
        }

        public Criteria andIsChangeTermGreaterThanOrEqualTo(String value) {
            addCriterion("is_change_term >=", value, "isChangeTerm");
            return (Criteria) this;
        }

        public Criteria andIsChangeTermLessThan(String value) {
            addCriterion("is_change_term <", value, "isChangeTerm");
            return (Criteria) this;
        }

        public Criteria andIsChangeTermLessThanOrEqualTo(String value) {
            addCriterion("is_change_term <=", value, "isChangeTerm");
            return (Criteria) this;
        }

        public Criteria andIsChangeTermLike(String value) {
            addCriterion("is_change_term like", value, "isChangeTerm");
            return (Criteria) this;
        }

        public Criteria andIsChangeTermNotLike(String value) {
            addCriterion("is_change_term not like", value, "isChangeTerm");
            return (Criteria) this;
        }

        public Criteria andIsChangeTermIn(List<String> values) {
            addCriterion("is_change_term in", values, "isChangeTerm");
            return (Criteria) this;
        }

        public Criteria andIsChangeTermNotIn(List<String> values) {
            addCriterion("is_change_term not in", values, "isChangeTerm");
            return (Criteria) this;
        }

        public Criteria andIsChangeTermBetween(String value1, String value2) {
            addCriterion("is_change_term between", value1, value2, "isChangeTerm");
            return (Criteria) this;
        }

        public Criteria andIsChangeTermNotBetween(String value1, String value2) {
            addCriterion("is_change_term not between", value1, value2, "isChangeTerm");
            return (Criteria) this;
        }

        public Criteria andMessageReplyStatusIsNull() {
            addCriterion("message_reply_status is null");
            return (Criteria) this;
        }

        public Criteria andMessageReplyStatusIsNotNull() {
            addCriterion("message_reply_status is not null");
            return (Criteria) this;
        }

        public Criteria andMessageReplyStatusEqualTo(Integer value) {
            addCriterion("message_reply_status =", value, "messageReplyStatus");
            return (Criteria) this;
        }

        public Criteria andMessageReplyStatusNotEqualTo(Integer value) {
            addCriterion("message_reply_status <>", value, "messageReplyStatus");
            return (Criteria) this;
        }

        public Criteria andMessageReplyStatusGreaterThan(Integer value) {
            addCriterion("message_reply_status >", value, "messageReplyStatus");
            return (Criteria) this;
        }

        public Criteria andMessageReplyStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("message_reply_status >=", value, "messageReplyStatus");
            return (Criteria) this;
        }

        public Criteria andMessageReplyStatusLessThan(Integer value) {
            addCriterion("message_reply_status <", value, "messageReplyStatus");
            return (Criteria) this;
        }

        public Criteria andMessageReplyStatusLessThanOrEqualTo(Integer value) {
            addCriterion("message_reply_status <=", value, "messageReplyStatus");
            return (Criteria) this;
        }

        public Criteria andMessageReplyStatusIn(List<Integer> values) {
            addCriterion("message_reply_status in", values, "messageReplyStatus");
            return (Criteria) this;
        }

        public Criteria andMessageReplyStatusNotIn(List<Integer> values) {
            addCriterion("message_reply_status not in", values, "messageReplyStatus");
            return (Criteria) this;
        }

        public Criteria andMessageReplyStatusBetween(Integer value1, Integer value2) {
            addCriterion("message_reply_status between", value1, value2, "messageReplyStatus");
            return (Criteria) this;
        }

        public Criteria andMessageReplyStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("message_reply_status not between", value1, value2, "messageReplyStatus");
            return (Criteria) this;
        }

        public Criteria andPopupStatusIsNull() {
            addCriterion("popup_status is null");
            return (Criteria) this;
        }

        public Criteria andPopupStatusIsNotNull() {
            addCriterion("popup_status is not null");
            return (Criteria) this;
        }

        public Criteria andPopupStatusEqualTo(Integer value) {
            addCriterion("popup_status =", value, "popupStatus");
            return (Criteria) this;
        }

        public Criteria andPopupStatusNotEqualTo(Integer value) {
            addCriterion("popup_status <>", value, "popupStatus");
            return (Criteria) this;
        }

        public Criteria andPopupStatusGreaterThan(Integer value) {
            addCriterion("popup_status >", value, "popupStatus");
            return (Criteria) this;
        }

        public Criteria andPopupStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("popup_status >=", value, "popupStatus");
            return (Criteria) this;
        }

        public Criteria andPopupStatusLessThan(Integer value) {
            addCriterion("popup_status <", value, "popupStatus");
            return (Criteria) this;
        }

        public Criteria andPopupStatusLessThanOrEqualTo(Integer value) {
            addCriterion("popup_status <=", value, "popupStatus");
            return (Criteria) this;
        }

        public Criteria andPopupStatusIn(List<Integer> values) {
            addCriterion("popup_status in", values, "popupStatus");
            return (Criteria) this;
        }

        public Criteria andPopupStatusNotIn(List<Integer> values) {
            addCriterion("popup_status not in", values, "popupStatus");
            return (Criteria) this;
        }

        public Criteria andPopupStatusBetween(Integer value1, Integer value2) {
            addCriterion("popup_status between", value1, value2, "popupStatus");
            return (Criteria) this;
        }

        public Criteria andPopupStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("popup_status not between", value1, value2, "popupStatus");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNull() {
            addCriterion("last_update_time is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNotNull() {
            addCriterion("last_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeEqualTo(Date value) {
            addCriterion("last_update_time =", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotEqualTo(Date value) {
            addCriterion("last_update_time <>", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThan(Date value) {
            addCriterion("last_update_time >", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_update_time >=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThan(Date value) {
            addCriterion("last_update_time <", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_update_time <=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIn(List<Date> values) {
            addCriterion("last_update_time in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotIn(List<Date> values) {
            addCriterion("last_update_time not in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("last_update_time between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_update_time not between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table e_user_message
     *
     * @mbggenerated do_not_delete_during_merge Tue Jul 06 08:37:32 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table e_user_message
     *
     * @mbggenerated Tue Jul 06 08:37:32 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}